// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nitgyshvzwhzczvvrxhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pdGd5c2h2endoemN6dnZyeGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTkxMDYsImV4cCI6MjA2MTA5NTEwNn0.GBNU7HGt1FR0Qu0ee7jA0703cZKGl7AA17izq8LcJBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);